services:
  mysql:
    image: mysql:latest
    container_name: mysql_ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommercedb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
