services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommercedb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: ecommercedb
